# Generated by Django 4.0.1 on 2022-01-27 21:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_event_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('sell_mode', models.CharField(choices=[(1, 'online'), (2, 'offline')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(unique=True)),
                ('event_date', models.DateTimeField()),
                ('sell_from', models.DateTimeField()),
                ('sell_to', models.DateTimeField()),
                ('sold_out', models.BooleanField()),
                ('base_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticdata.baseevent')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.CharField(db_index=True, max_length=32)),
                ('level', models.IntegerField(choices=[(10, 'Debug'), (20, 'Info'), (30, 'Warning'), (40, 'Error'), (50, 'Critical')])),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('numbered', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticdata.event')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticdata.zone')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='zones',
            field=models.ManyToManyField(through='staticdata.EventZone', to='staticdata.Zone'),
        ),
    ]
