# Generated by Django 4.0.1 on 2022-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='sell_mode',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=40),
        ),
    ]
